[tool.poetry]
name = "eyepacs"
version = "0.1.0"
description = ""
authors = ["facundoq <facundoq@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
torchvision = "*"
kaggle =  "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
